export const projects = [
  {
    id: 1,
    category: "Frontend",
    name: "Rock, Paper N scissors",
    previewImg: "/Images/Projects/rock-paper-scissors.png",
    liveLink: "https://rock-paper-scissors-psi-ten.vercel.app/",
  },
  {
    id: 2,
    category: "Frontend",
    name: "Budget Stats",
    previewImg: "/Images/Projects/budgetstats.png",
    liveLink: "https://budget-stats.vercel.app/",
  },
  {
    id: 3,
    category: "Frontend",
    name: "MiniProFeb25",
    previewImg: "/Images/Projects/miniprojectfebcohort2025.png",
    liveLink: "feb-cohort-2025-mini-project-olive.vercel.app/",
  },
  // {
  //   id: 4,
  //   category: "Frontend",
  //   name: "Rock, Scissor N Paper",
  //   previewImg: "",
  //   liveLink: "",
  // },
  // {
  //   id: 5,
  //   category: "Frontend",
  //   name: "Rock, Scissor N Paper",
  //   previewImg: "",
  //   liveLink: "",
  // },
  // {
  //   id: 6,
  //   category: "Visual and UX Design",
  //   name: "Rock, Scissor N Paper",
  //   previewImg: "",
  //   liveLink: "",
  // },
  // {
  //   id: 7,
  //   category: "Visual and UX Design",
  //   name: "Rock, Scissor N Paper",
  //   previewImg: "",
  //   liveLink: "",
  // },
  // {
  //   id: 8,
  //   category: "Visual and UX Design",
  //   name: "Rock, Scissor N Paper",
  //   previewImg: "",
  //   liveLink: "",
  // },
  // {
  //   id: 9,
  //   category: "Visual and UX Design",
  //   name: "Rock, Scissor N Paper",
  //   previewImg: "",
  //   liveLink: "",
  // },
  // {
  //   id: 10,
  //   category: "Visual and UX Design",
  //   name: "Rock, Scissor N Paper",
  //   previewImg: "",
  //   liveLink: "",
  // },
];
