export const textTestimonals = [
  {
    id: 1,
    name: "Abigail",
    role: "Frontend Developer",
    text: `When I got my first computer, I knew nothing about tech. I joined Cybite Academy’s Frontend course as a complete beginner, and it changed everything for me. The lessons were easy to follow, and the support was amazing. Today, I work as a freelance frontend developer and have built real projects for clients. I never imagined I’d come this far so quickly.`,
    image: "/Images/TextImages/abigail.jpeg",
  },
  {
    id: 2,
    name: "Lawal",
    role: "Business Owner & Graphic Designer",
    text: `Before joining Cybite Academy, I ran my business without really understanding how to present it online. After taking the graphics and frontend development courses, everything changed. I now design my own branding and manage my website and I ave seen a real boost. The skills I gained aren’t just technical they are practical and helping my me grow everyday.`,
    image: "",
  },
  {
    id: 3,
    name: "Mr. Stanley",
    role: "Business Owner & Graphic Designer",
    text: `As a business owner, I used to rely on designers for every flyer or visual I needed it was time-consuming and expensive. After taking the Visual & Design course at Cybite Academy, I can now create all my designs myself. It’s given me more creative freedom and control over how my brand looks and communicates. I highly recommend the program to any entrepreneur who wants to level up.`,
    image: "",
  },
  {
    id: 4,
    name: "Mike",
    role: "Music Promoter & Visual Designer",
    text: `As a music promoter, visuals are everything from event flyers to social media content. Before Cybite Academy, I always had to rely on others for designs. Taking the Visual & Design course gave me the skills to do it all myself. Now, I create professional designs that truly reflect my brand, and it’s made a big difference in how people engage with my work.`,
    image: "/Images/TextImages/mike.jpeg",
  },
  {
    id: 5,
    name: "Daniel",
    role: "Frontend Developer",
    text: `I just finished secondary school and wanted to get a head start before studying computer science. Joining Cybite Academy’s Frontend course has been a game-changer. I’m learning the real, practical side of tech not just theory. Now I can build websites from scratch and I feel more confident about my future in tech.`,
    image: "/Images/TextImages/daniel.jpeg",
  },
  {
    id: 6,
    name: "Halima",
    role: "Frontend Developer",
    text: `Learning both frontend development and design at Cybite Academy was one of the best decisions I’ve made. Before heading out for NYSC, I completed both courses and those skills helped me land a tech job right after. Cybite didn’t just teach me theory; they gave me the real-world skills companies are looking for.`,
    image: "",
  },
  {
    id: 7,
    name: "Michael",
    role: "Frontend Developer & Cybite Academy SIWES Intern",
    text: `I did my SIWES at Cybite Academy and focused on frontend web development. The experience was hands-on and practical way beyond what I was used to at school. Now, I build real projects, help my course mates with theirs, and even earn from it. Cybite gave me the skills and confidence to start making money with what I’ve learned.`,
    image: "/Images/TextImages/michael.jpeg",
  },
];
